window.LITERATURE_DATA = {
  meta: {
    version: "0.2.0",
    lastUpdated: "2026-04-20",
  },
  modelLabels: {
    qpm: { en: "QPM", ru: "КПМ", uz: "CPM" },
    dfm: { en: "DFM", ru: "ДФМ", uz: "DFM" },
    cge: { en: "CGE", ru: "CGE", uz: "CGE" },
    io: { en: "Input-Output", ru: "Межотраслевой баланс", uz: "Tarmoqlararo balans" },
    pe: { en: "Partial Equilibrium", ru: "Частичное равновесие", uz: "Qisman muvozanat" },
    fpp: { en: "FPP", ru: "ФПП", uz: "MDS" },
  },
  papers: [
    /* ── QPM ── */
    {
      id: "berg-2006-qpm",
      model: "qpm",
      topic: "monetary",
      title: "Quarterly Projection Model for Small Open Economies",
      authors: "Berg, A., Karam, P., Laxton, D.",
      year: 2006,
      venue: "IMF Working Paper WP/06/185",
      doi: "10.5089/9781451863322.001",
      url: "https://www.imf.org/external/pubs/ft/wp/2006/wp06185.pdf",
      abstract: "Develops a tractable quarterly projection model for inflation-targeting central banks in small open economies, with IS curve, Phillips curve, Taylor rule, and UIP.",
      relevance: {
        en: "Foundational design template for the QPM — IS/Phillips/Taylor/UIP structure and calibration approach.",
        ru: "Базовый шаблон построения КПМ — структура IS/Филлипса/Тейлора/UIP и подход к калибровке.",
        uz: "CPM uchun asosiy dizayn andozasi — IS/Fillips/Teylor/UIP tuzilishi va kalibrlash yondashuvi.",
      },
    },
    {
      id: "laxton-2009-fpas",
      model: "qpm",
      topic: "monetary",
      title: "The Forecasting and Policy Analysis System at the Central Bank of Chile",
      authors: "Laxton, D., Rose, D., Scott, A.",
      year: 2009,
      venue: "IMF Working Paper WP/09/29",
      doi: "10.5089/9781451871654.001",
      url: "https://www.imf.org/external/pubs/ft/wp/2009/wp0929.pdf",
      abstract: "Operational architecture linking core QPM model to forecast rounds, fan charts, and policy communication at a central bank.",
      relevance: {
        en: "Useful for institutionalizing the forecast-policy workflow around the QPM at the CBU.",
        ru: "Полезно для институционализации цикла прогноз-политика вокруг КПМ в ЦБ.",
        uz: "MB da CPM atrofida prognoz-siyosat ish jarayonini tashkil etishda foydali.",
      },
    },
    {
      id: "imf-qpm-low-income-2017",
      model: "qpm",
      topic: "monetary",
      title: "Monetary Policy Transmission in Developing Countries: Evidence from India",
      authors: "Mishra, P., Montiel, P., Spilimbergo, A.",
      year: 2012,
      venue: "IMF Working Paper WP/12/143",
      doi: "10.5089/9781475504101.001",
      url: "https://www.imf.org/external/pubs/ft/wp/2012/wp12143.pdf",
      abstract: "Examines monetary policy transmission in developing countries with underdeveloped financial markets, relevant to QPM calibration for Uzbekistan.",
      relevance: {
        en: "Informs QPM calibration for economies with weak monetary transmission and shallow FX markets.",
        ru: "Информирует калибровку КПМ для экономик со слабой денежной трансмиссией.",
        uz: "Pul-kredit uzatmasi zaif iqtisodiyotlar uchun CPM kalibrlashni ma'lumot bilan ta'minlaydi.",
      },
    },

    /* ── DFM ── */
    {
      id: "banbura-2014-dfm",
      model: "dfm",
      topic: "nowcasting",
      title: "Maximum Likelihood Estimation of Factor Models on Datasets with Arbitrary Pattern of Missing Data",
      authors: "Banbura, M., Modugno, M.",
      year: 2014,
      venue: "Journal of Applied Econometrics, 29(1), 133-160",
      doi: "10.1002/jae.2306",
      url: "https://onlinelibrary.wiley.com/doi/10.1002/jae.2306",
      abstract: "ML estimation approach for large mixed-frequency datasets with ragged edges and arbitrary missing patterns.",
      relevance: {
        en: "Core methodology for handling missing data in the DFM Kalman filter nowcasting engine.",
        ru: "Основная методология обработки пропусков в системе nowcast DFM на основе фильтра Калмана.",
        uz: "DFM Kalman filtri nowcast tizimida yetishmayotgan ma'lumotlarni qayta ishlash metodologiyasi.",
      },
    },
    {
      id: "giannone-2008-nowcasting",
      model: "dfm",
      topic: "nowcasting",
      title: "Nowcasting: The Real-Time Informational Content of Macroeconomic Data",
      authors: "Giannone, D., Reichlin, L., Small, D.",
      year: 2008,
      venue: "Journal of Monetary Economics, 55(4), 665-676",
      doi: "10.1016/j.jmoneco.2008.05.010",
      url: "https://doi.org/10.1016/j.jmoneco.2008.05.010",
      abstract: "Classical nowcasting framework combining staggered data releases into current-quarter GDP estimates via dynamic factor models.",
      relevance: {
        en: "Canonical reference for release-calendar aware nowcasting and news decomposition.",
        ru: "Каноническая работа по nowcast с учетом календаря публикаций и разложению новостей.",
        uz: "Nashr taqvimi hisobga olingan nowcast va yangiliklar dekompozitsiyasi uchun klassik manba.",
      },
    },
    {
      id: "doz-2012-em-dfm",
      model: "dfm",
      topic: "nowcasting",
      title: "A Quasi-Maximum Likelihood Approach for Large, Approximate Dynamic Factor Models",
      authors: "Doz, C., Giannone, D., Reichlin, L.",
      year: 2012,
      venue: "Review of Economics and Statistics, 94(4), 1014-1024",
      doi: "10.1162/REST_a_00225",
      url: "https://doi.org/10.1162/REST_a_00225",
      abstract: "Two-step QML estimation combining principal components with Kalman smoothing for large panel datasets.",
      relevance: {
        en: "Alternative estimation approach relevant to scaling DFM with 34+ indicators.",
        ru: "Альтернативный подход к оценке для масштабирования DFM с 34+ индикаторами.",
        uz: "34+ ko'rsatkichlar bilan DFMni kengaytirish uchun muqobil baholash yondashuvi.",
      },
    },

    /* ── CGE ── */
    {
      id: "devarajan-1990-cge",
      model: "cge",
      topic: "trade",
      title: "Simple General Equilibrium Modeling",
      authors: "Devarajan, S., Lewis, J., Robinson, S.",
      year: 1990,
      venue: "World Development, 18(10), 1375-1398",
      doi: "10.1016/0305-750X(90)90006-2",
      url: "https://doi.org/10.1016/0305-750X(90)90006-2",
      abstract: "Compact CGE structure suitable for policy counterfactuals in developing economies with limited data.",
      relevance: {
        en: "Methodological backbone for the 1-2-3 style CGE module — CET/CES/closure approach.",
        ru: "Методологическая основа модуля CGE 1-2-3 — подход CET/CES/замыкание.",
        uz: "CGE 1-2-3 moduli uchun metodologik asos — CET/CES/yopilish yondashuvi.",
      },
    },
    {
      id: "devarajan-1997-123",
      model: "cge",
      topic: "trade",
      title: "The 1-2-3 DSGE Model: A Practical Guide for Analysis in Developing Countries",
      authors: "Devarajan, S., Go, D., Lewis, J., Robinson, S., Sinko, P.",
      year: 1997,
      venue: "World Bank Policy Research Working Paper No. 1893",
      doi: "10.1596/1813-9450-1893",
      url: "https://doi.org/10.1596/1813-9450-1893",
      abstract: "Practical closure rules, calibration guidance, and worked examples for trade and fiscal experiments in the 1-2-3 framework.",
      relevance: {
        en: "Provides the closure conventions and calibration protocols used in Uzbekistan CGE simulations.",
        ru: "Дает правила замыкания и протоколы калибровки для CGE-симуляций Узбекистана.",
        uz: "O'zbekiston CGE simulyatsiyalari uchun yopilish qoidalari va kalibrlash protokollarini beradi.",
      },
    },
    {
      id: "armington-1969",
      model: "cge",
      topic: "trade",
      title: "A Theory of Demand for Products Distinguished by Place of Production",
      authors: "Armington, P.S.",
      year: 1969,
      venue: "IMF Staff Papers, 16(1), 159-178",
      doi: "10.2307/3866403",
      url: "https://doi.org/10.2307/3866403",
      abstract: "Foundational import-demand assumption distinguishing goods by origin, used in virtually all applied CGE models.",
      relevance: {
        en: "Theoretical basis for the CES import-substitution block (σ_q = 0.70) in the CGE module.",
        ru: "Теоретическая основа блока импортозамещения CES (σ_q = 0.70) в модуле CGE.",
        uz: "CGE modulidagi CES import o'rnini bosish bloki (σ_q = 0.70) uchun nazariy asos.",
      },
    },
    {
      id: "lofgren-2002-standard-cge",
      model: "cge",
      topic: "trade",
      title: "A Standard Computable General Equilibrium Model in GAMS",
      authors: "Lofgren, H., Harris, R., Robinson, S.",
      year: 2002,
      venue: "IFPRI TMD Discussion Paper No. 75",
      doi: "",
      url: "https://www.ifpri.org/publication/standard-computable-general-equilibrium-cge-model-gams",
      abstract: "Standard CGE model documentation with SAM-based calibration, widely used as reference implementation.",
      relevance: {
        en: "Reference implementation for CGE calibration from SAM data — informs our 2021 base-year setup.",
        ru: "Эталонная реализация калибровки CGE из SAM — информирует нашу настройку базового 2021 года.",
        uz: "SAM ma'lumotlaridan CGE kalibrlashning etalon amalga oshirilishi — 2021 bazaviy yil sozlamalarini shakllantiradi.",
      },
    },

    /* ── IO ── */
    {
      id: "leontief-1986-io",
      model: "io",
      topic: "multipliers",
      title: "Input-Output Economics",
      authors: "Leontief, W.",
      year: 1986,
      venue: "Oxford University Press (2nd edition)",
      doi: "10.1093/0195035275.001.0001",
      url: "https://global.oup.com/academic/product/input-output-economics-9780195035278",
      abstract: "Foundational treatment of inter-industry linkage analysis, technical coefficients, and multiplier mechanics.",
      relevance: {
        en: "Primary conceptual source for output and value-added multiplier interpretation in the 136-sector model.",
        ru: "Базовый источник для интерпретации мультипликаторов выпуска и ДС в 136-секторной модели.",
        uz: "136-tarmoqli modelda ishlab chiqarish va QQ multiplikatorlarini talqin qilishning asosiy manbasi.",
      },
    },
    {
      id: "miller-blair-2009",
      model: "io",
      topic: "multipliers",
      title: "Input-Output Analysis: Foundations and Extensions",
      authors: "Miller, R.E., Blair, P.D.",
      year: 2009,
      venue: "Cambridge University Press (2nd edition)",
      doi: "10.1017/CBO9780511626982",
      url: "https://doi.org/10.1017/CBO9780511626982",
      abstract: "Comprehensive modern reference on I-O coefficients, Type I/II multipliers, structural decomposition, and regional extensions.",
      relevance: {
        en: "Supports multiplier diagnostics, Rasmussen classification, and sector linkage analysis.",
        ru: "Поддерживает диагностику мультипликаторов, классификацию Расмуссена и анализ отраслевых связей.",
        uz: "Multiplikator diagnostikasi, Rasmussen klassifikatsiyasi va tarmoq aloqalari tahlilini qo'llab-quvvatlaydi.",
      },
    },
    {
      id: "temursho-2017-io",
      model: "io",
      topic: "multipliers",
      title: "Analytical and Empirical Comparisons of Input-Output Multipliers",
      authors: "Temursho, U.",
      year: 2017,
      venue: "Journal of Economic Surveys, 31(3), 921-940",
      doi: "10.1111/joes.12167",
      url: "https://doi.org/10.1111/joes.12167",
      abstract: "Systematic comparison of Type I, II, and SAM-based multipliers with empirical evidence on bias and policy relevance.",
      relevance: {
        en: "Informs choice between Type I (current) and Type II multipliers for future IO model upgrades.",
        ru: "Информирует выбор между мультипликаторами Типа I (текущий) и Типа II для будущих обновлений МОБ.",
        uz: "Kelajakdagi MOB yangilanishlari uchun I Tip (joriy) va II Tip multiplikatorlari o'rtasida tanlashga yordam beradi.",
      },
    },

    /* ── PE ── */
    {
      id: "wits-smart-guide",
      model: "pe",
      topic: "trade",
      title: "WITS-SMART Simulation Tool: User Guide and Methodology",
      authors: "World Bank WITS Team",
      year: 2020,
      venue: "World Bank Technical Manual",
      doi: "",
      url: "https://wits.worldbank.org/wits/wits/witshelp/Content/SMART/SMART.htm",
      abstract: "Documentation of SMART partial equilibrium formulas for trade creation, trade diversion, consumer surplus, and tariff revenue calculations.",
      relevance: {
        en: "Direct specification source for PE trade creation/diversion formulas (TC, TD, welfare).",
        ru: "Прямой источник спецификации формул создания/отклонения торговли в модели ЧР.",
        uz: "QM savdo yaratish/chetga surilish formulalari uchun bevosita spetsifikatsiya manbasi.",
      },
    },
    {
      id: "laird-yeats-1990",
      model: "pe",
      topic: "trade",
      title: "Quantitative Methods for Trade Barrier Analysis",
      authors: "Laird, S., Yeats, A.",
      year: 1990,
      venue: "London: Macmillan",
      doi: "10.1007/978-1-349-20685-3",
      url: "https://doi.org/10.1007/978-1-349-20685-3",
      abstract: "Classical partial-equilibrium methods for tariff incidence, effective protection, and welfare analysis of trade liberalization.",
      relevance: {
        en: "Provides assumptions and interpretation standards for PE welfare metrics used in WTO scenarios.",
        ru: "Задает предпосылки и стандарты интерпретации показателей благосостояния для сценариев ВТО.",
        uz: "VTS stsenariylari uchun farovonlik ko'rsatkichlarini talqin qilish standartlarini beradi.",
      },
    },
    {
      id: "brenton-2001-wto",
      model: "pe",
      topic: "trade",
      title: "Trade Policy Reform and the WTO Accession of Transition Economies",
      authors: "Brenton, P., Manchin, M.",
      year: 2003,
      venue: "World Bank Policy Research Working Paper No. 3012",
      doi: "10.1596/1813-9450-3012",
      url: "https://doi.org/10.1596/1813-9450-3012",
      abstract: "Analysis of WTO accession trade impacts for transition economies using partial equilibrium methods.",
      relevance: {
        en: "Directly relevant to Uzbekistan's WTO accession trade impact analysis using PE methods.",
        ru: "Непосредственно относится к анализу торговых последствий вступления Узбекистана в ВТО.",
        uz: "O'zbekistonning VSTga qo'shilishining savdoga ta'sirini QM usullari bilan tahlil qilishga bevosita aloqador.",
      },
    },

    /* ── FPP ── */
    {
      id: "imf-fp-manual-2013",
      model: "fpp",
      topic: "fiscal",
      title: "Financial Programming and Policies",
      authors: "IMF Institute for Capacity Development",
      year: 2013,
      venue: "IMF Training Manual (2 volumes)",
      doi: "",
      url: "https://www.imf.org/en/Capacity-Development/Training/ICDTC/Courses/FPP",
      abstract: "Integrated macro-consistency framework linking real, fiscal, external, and monetary sectors through accounting identities and behavioral equations.",
      relevance: {
        en: "Core reference for the 4-sector consistency checks and accounting identities in the FPP module.",
        ru: "Ключевой источник по 4-секторным проверкам согласованности и тождествам в модуле ФПП.",
        uz: "MDS modulidagi 4-sektorli moslik tekshiruvlari va hisob identifikatsiyalari uchun asosiy manba.",
      },
    },
    {
      id: "mussa-savastano-1999",
      model: "fpp",
      topic: "fiscal",
      title: "The IMF Approach to Economic Stabilization",
      authors: "Mussa, M., Savastano, M.",
      year: 1999,
      venue: "NBER Macroeconomics Annual 1999, Vol. 14, 79-122",
      doi: "10.1086/654424",
      url: "https://doi.org/10.1086/654424",
      abstract: "Discussion of IMF stabilization program design, policy consistency checks, and conditionality trade-offs.",
      relevance: {
        en: "Useful framing for translating FPP simulation outputs into stabilization policy narratives.",
        ru: "Полезная рамка для перевода результатов ФПП в рекомендации по стабилизационной политике.",
        uz: "MDS simulyatsiya natijalarini barqarorlashtirish siyosati tavsiyalariga aylantirish uchun foydali yondashuv.",
      },
    },
    {
      id: "polak-1957-monetary",
      model: "fpp",
      topic: "monetary",
      title: "Monetary Analysis of Income Formation and Payments Problems",
      authors: "Polak, J.J.",
      year: 1957,
      venue: "IMF Staff Papers, 6(1), 1-50",
      doi: "10.2307/3866128",
      url: "https://doi.org/10.2307/3866128",
      abstract: "The foundational monetary approach to the balance of payments — origin of the IMF Financial Programming framework.",
      relevance: {
        en: "Historical foundation of the monetary-BOP link in financial programming (NFA + NDA = M2).",
        ru: "Историческая основа связи монетарный сектор — платежный баланс в ФП (ЧИА + ЧВА = M2).",
        uz: "Moliyaviy dasturlashdagi pul-to'lov balansi aloqasining tarixiy asosi (STF + IKA = M2).",
      },
    },
    {
      id: "totem-the-bank-of-canada-s-new-quarterl-2006",
      model: "qpm",
      topic: "methodology",
      title: "ToTEM: The Bank of Canada's New Quarterly Projection Model",
      authors: "Stephen Murchison, A. Rennison",
      year: 2006,
      venue: "",
      doi: "",
      abstract: "",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "the-bank-of-canada-s-new-quarterly-proje-1996",
      model: "qpm",
      topic: "methodology",
      title: "The Bank of Canada's New Quarterly Projection Model, Part 3. The Dynamic Model: QPM",
      authors: "D. Coletti, Benjamin L Hunt, David Rose, R. Tetlow",
      year: 1996,
      venue: "",
      doi: "",
      abstract: "",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "the-bank-of-canada-s-new-quarterly-proje-1994",
      model: "qpm",
      topic: "methodology",
      title: "The Bank of Canada's new Quarterly Projection Model (QPM): An introduction",
      authors: "Stephen S. Poloz, David Rose, R. Tetlow",
      year: 1994,
      venue: "",
      doi: "",
      abstract: "",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "quarterly-projection-model-for-the-natio-2020",
      model: "qpm",
      topic: "methodology",
      title: "Quarterly Projection Model for the National Bank of Rwanda",
      authors: "Jan Vlček, M. Pranovich, P. Hitayezu, Bruno Mwenese, Christian Nyalihama",
      year: 2020,
      venue: "IMF Working Papers",
      doi: "10.5089/9781513564630.001.A001",
      abstract: "National Bank of Rwanda (BNR) modernized monetary policy and transited to the price-based policy framework in January 2019. The Forecasting and Policy Analysis System (FPAS) is the cornerstone for the new forward-looking framework, which mobilizes and organizes resources and sets processes for regular forecasting rounds. The core of this system is a structural macroeconomic model for macroeconomic analysis and projections to support the BNR staff’s policy recommendations to the monetary policy c",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "bayesian-estimation-of-a-simple-macroeco-2010",
      model: "qpm",
      topic: "methodology",
      title: "Bayesian Estimation of a Simple Macroeconomic Model for a Small Open and Partially Dollarized Economy",
      authors: "J. Salas",
      year: 2010,
      venue: "",
      doi: "",
      abstract: "",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "nowcasting-us-gdp-using-tree-based-ensem-2021",
      model: "dfm",
      topic: "methodology",
      title: "Nowcasting US GDP Using Tree-Based Ensemble Models and Dynamic Factors",
      authors: "Barış Soybilgen, Ege Yazgan",
      year: 2021,
      venue: "Computational Economics",
      doi: "10.1007/s10614-020-10083-5",
      abstract: "",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "determining-number-of-factors-in-dynamic-2021",
      model: "dfm",
      topic: "methodology",
      title: "Determining Number of Factors in Dynamic Factor Models Contributing to GDP Nowcasting",
      authors: "Jiayi Luo, Cindy Yu",
      year: 2021,
      venue: "Mathematics",
      doi: "10.3390/math9222865",
      abstract: "Real-time nowcasting is a process to assess current-quarter GDP from timely released economic and financial series before the figure is disseminated in order to catch the overall macroeconomic conditions in real time. In economic data nowcasting, dynamic factor models (DFMs) are widely used due to their abilities to bridge information with different frequencies and to achieve dimension reduction. However, most of the research using DFMs assumes a fixed known number of factors contributing to GDP",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "a-three-frequency-dynamic-factor-model-f-2020",
      model: "dfm",
      topic: "methodology",
      title: "A three-frequency dynamic factor model for nowcasting Canadian provincial GDP growth",
      authors: "Tony Chernis, Calista Cheung, Gabriella Velasco",
      year: 2020,
      venue: "International Journal of Forecasting",
      doi: "10.1016/j.ijforecast.2019.09.006",
      abstract: "",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "implementing-an-approximate-dynamic-fact-2018",
      model: "dfm",
      topic: "methodology",
      title: "Implementing an Approximate Dynamic Factor Model to Nowcast GDP Using Sensitivity Analysis",
      authors: "Paulo Duarte, Bernd Süßmuth",
      year: 2018,
      venue: "Journal of Business Cycle Research",
      doi: "10.1007/s41549-018-0026-0",
      abstract: "",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "nowcasting-brazilian-gdp-a-performance-2018",
      model: "dfm",
      topic: "methodology",
      title: "Nowcasting Brazilian GDP: a performance assessment of dynamic factor models",
      authors: "Guilherme Branco Gomes",
      year: 2018,
      venue: "Americanae (AECID Library)",
      doi: "",
      abstract: "This work compares dynamic factor model’s forecasts for Brazilian GDP. Our approach takes into account mixed frequencies and can handle missing data. We implement three models: the first is based on the Principal Components Analysis methodology; the second employs a two-step estimation method with quarterly inputs; the last is similar to the former but uses monthly series. A real-time out-of-sample exercise is proposed to assess the performance of these models. A dataset is created for each day ",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "linking-armington-and-cet-elasticities-o-2017",
      model: "cge",
      topic: "methodology",
      title: "Linking Armington and CET Elasticities of Substitution and Transformation to Price Elasticities of Import Demand and Export Supply: A Note for CGE Practitioners",
      authors: "Hans Löfgren, Martín Cicowiez",
      year: 2017,
      venue: "El Servicio de Difusión de la Creación Intelectual (National University of La Plata)",
      doi: "10.13140/rg.2.2.34084.07046",
      abstract: "Armington and constant-elasticity-of-transformation (CET) functions are routinely used in computable general equilibrium (CGE) Models to model foreign trade. The CET function is applied to producer decisions about whether to export and or sell at home. Decisions by domestic demanders whether to purchase imports or domestic output are covered by the Armington function. The Armington function is a constant-elasticity-of-substitution (CES) function. This note is concerned with the links between (a)",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "how-pro-poor-and-income-equitable-are-to-2016",
      model: "cge",
      topic: "methodology",
      title: "How Pro-Poor and Income Equitable Are Tourism Taxation Policies in a Developing Country? Evidence from a Computable General Equilibrium Model",
      authors: "Renuka Mahadevan, Hidayat Amir, Anda Nugroho",
      year: 2016,
      venue: "Journal of Travel Research",
      doi: "10.1177/0047287516641781",
      abstract: "This article highlights the impacts on poverty, income inequality, and the macroeconomic and sectoral output resulting from increases in the value-added tax and sales tax on hotels and restaurants using Indonesia as a case study. While taxing tourism-related sectors was ineffective in reducing poverty and income inequality, using tax revenue from the value-added tax as a cash transfer policy was effective and more so in rural Indonesia. Tax revenue used for infrastructural development was howeve",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "assessing-direct-and-indirect-economic-i-2015",
      model: "cge",
      topic: "methodology",
      title: "Assessing direct and indirect economic impacts of a flood event through the integration of spatial and computable general equilibrium modelling",
      authors: "Standardi, G., Bosello, F.",
      year: 2015,
      venue: "Archivio Istituzionale della Ricerca (Universita Degli Studi Di Milano)",
      doi: "10.1016/j.envsoft.2014.09.016",
      abstract: "",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "trade-liberalization-and-labor-market-dy-2014",
      model: "cge",
      topic: "methodology",
      title: "Trade Liberalization and Labor Market Dynamics",
      authors: "Rafael Dix-Carneiro",
      year: 2014,
      venue: "Econometrica",
      doi: "10.3982/ecta10457",
      abstract: "This paper estimates a structural dynamic equilibrium model of the Brazilian labor market in order to study trade-induced transitional dynamics. The model features a multi-sector economy with overlapping generations, heterogeneous workers, endogenous accumulation of sector-specific experience, and costly switching of sectors. The model's estimates yield median costs of mobility ranging from 1.4 to 2.7 times annual average wages, but a high dispersion of these costs across the population. In addi",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "an-overview-of-the-oecd-env-linkages-mod-2014",
      model: "cge",
      topic: "methodology",
      title: "An Overview of the OECD ENV-Linkages Model",
      authors: "Jean Château, Rob Dellink, Elisa Lanzi",
      year: 2014,
      venue: "OECD environment working papers",
      doi: "10.1787/5jz2qck2b2vd-en",
      abstract: "This document provides a detailed technical description of the ENV-Linkages model. The OECD ENV-Linkages Computable General Equilibrium (CGE) model is an economic model that describes how economic activities are inter-linked across several macroeconomic sectors and regions. It links economic activity to environmental pressure, specifically to emissions of greenhouse gases (GHGs). The links between economic activities and emissions are projected for several decades into the future, and thus shed ",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "input-output-analysis-and-interrelationa-1968",
      model: "io",
      topic: "methodology",
      title: "Input-Output Analysis and Interrelational Income Multiplier as a Matrix",
      authors: "K. Miyazawa",
      year: 1968,
      venue: "",
      doi: "10.1007/978-3-642-48146-8_2",
      abstract: "",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "multiplier-effects-by-sector-an-input-o-2020",
      model: "io",
      topic: "methodology",
      title: "Multiplier effects by sector: an input-output analysis of the Greek economy",
      authors: "Constantina Bakinezos, S. Panagiotou, Evangelia Vourvachaki",
      year: 2020,
      venue: "",
      doi: "10.52903/ECONBULL20205201",
      abstract: "This study presents the output, gross value added and employment multipliers for the Greek economy based on the most recent Input-Output tables of 2015, which were compiled according to the European System of Accounts (ESA) 2010. The analysis utilises the Leontief model, in both the “open” and “closed” variations with respect to households’ consumption, which allows to assess, at a disaggregated sectoral level, the direct and indirect production effects, as well as the induced consumption effect",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "the-development-of-water-multiplier-impa-1976",
      model: "io",
      topic: "methodology",
      title: "The development of water multiplier impacts from input‐output analysis: An empirical example from Boulder, Larimer, and Weld Counties, Colorado",
      authors: "S. Gray, J. Mckean",
      year: 1976,
      venue: "",
      doi: "10.1029/WR012I002P00135",
      abstract: "",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "an-analysis-of-backward-and-forward-link-2021",
      model: "io",
      topic: "methodology",
      title: "An Analysis of Backward and Forward Linkages of Pharmaceutical Sector in India Based on an Input- Output Model",
      authors: "Manish Das, A. Kashyap",
      year: 2021,
      venue: "Journal of Pharmaceutical Research International",
      doi: "10.9734/jpri/2021/v33i63a35206",
      abstract: "Aims: The paper study about the inter-linkages between pharmaceutical sector and other sectors of Indian economy. The paper also measures the effects of growth in pharmaceutical sector on other sector’s growth.  Study Design: The study is mainly a static analysis based on secondary data concentrated in studying the production structure of Indian pharmaceutical sector.   Duration of Study: The time taken for the research to be completed is for a period of four months.  Methodology: We have used t",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "industry-specific-multipliers-to-identif-2017",
      model: "io",
      topic: "methodology",
      title: "Industry Specific Multipliers to Identify Key Industries of Indian Economy: An Application of Input Output Analysis",
      authors: "Priyanka Tariyal",
      year: 2017,
      venue: "",
      doi: "",
      abstract: "",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "modeling-the-interplay-between-sanitary-2017",
      model: "pe",
      topic: "methodology",
      title: "Modeling the Interplay between Sanitary and Phytosanitary Measures and Tariff‐rate Quotas under Partial Trade Liberalization",
      authors: "Jayson Beckman, Shawn Arita",
      year: 2017,
      venue: "",
      doi: "10.1093/ajae/aaw056",
      abstract: "",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "trade-liberalization-and-pollution-inten-2001",
      model: "pe",
      topic: "methodology",
      title: "Trade Liberalization and Pollution Intensive Industries in Developing Countries: A Partial Equilibrium Approach",
      authors: "F. Ackerman, K. Gallagher",
      year: 2001,
      venue: "",
      doi: "",
      abstract: "",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "food-trade-openness-and-enhancement-of-f-2021",
      model: "pe",
      topic: "methodology",
      title: "Food Trade Openness and Enhancement of Food Security—Partial Equilibrium Model Simulations for Selected Countries",
      authors: "E. Fathelrahman, S. Davies, S. Muhammad",
      year: 2021,
      venue: "Sustainability",
      doi: "10.3390/SU13084107",
      abstract: "This research measured the welfare impacts of food trade liberalization in India, Egypt, Pakistan, Saudi Arabia, and the United Arab Emirates (UAE) using the partial equilibrium model—World Integrated Trade Solution (WITS). Macroeconomic settings, domestic policy objectives, and food security indicator data are used to assess the implications of the simulations on food availability and stability. Simulation results for India, Egypt, and Pakistan indicate annual welfare gains (consumer surplus) o",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "agricultural-trade-liberalization-and-gr-2005",
      model: "pe",
      topic: "methodology",
      title: "Agricultural Trade Liberalization and Greenhouse Gas Emissions: Modeling the Linkages Using a Partial Equilibrium Trade Model",
      authors: "C. Saunders, A. Wreford",
      year: 2005,
      venue: "Agricultural and Resource Economics Review",
      doi: "10.1017/S1068280500001556",
      abstract: "",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "trade-liberalization-and-capital-flows-i-2025",
      model: "pe",
      topic: "methodology",
      title: "Trade Liberalization and Capital Flows in Nigeria: A Partial Equilibrium Analysis",
      authors: "C. Ezekwe",
      year: 2025,
      venue: "Social Science Research Network",
      doi: "10.2139/ssrn.5123539",
      abstract: "This study explores the link between trade liberalization and Capital flows in Nigeria between 1986 and 2015. The objectives were to:determine the effects of level of trade openness, tariff reduction, exchange rate differential and economy size on foreign direct investment in Nigeria. The required datasets were adapted from World Bank World Development Indicators, United Nations Conference on Trade and Development and Central Bank of Nigeria Statistical Bulletin. The study adopted a partial equi",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "comparative-analysis-of-fiscal-regulatio-2021",
      model: "fpp",
      topic: "methodology",
      title: "Comparative Analysis of Fiscal Regulation Measures of the G20 Countries in the Era of the Coronavirus Crisis and in the Post-Coronavirus Perspective",
      authors: "Alexander Pogorletskiy, Natalia Pokrovskaia",
      year: 2021,
      venue: "Journal of Applied Economic Research",
      doi: "10.15826/vestnik.2021.20.1.002",
      abstract: "The article seeks to describe the features of fiscal policy during the Covid-19 pandemic. The research subject is the developed and developing countries of the G20 Group. The purpose of the article is to show an increasing importance of fiscal regulation measures in the era of the coronavirus crisis and in the post-coronavirus future, while noting the special role of taxation, which in modern conditions is given an important role in the toolkit for replenishing the revenue of state budgets of th",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "fiscal-strategy-as-an-instrument-of-econ-2019",
      model: "fpp",
      topic: "methodology",
      title: "FISCAL STRATEGY AS AN INSTRUMENT OF ECONOMIC GROWTH",
      authors: "Ігор Чугунов, Valentyna Makohon",
      year: 2019,
      venue: "Baltic Journal of Economic Studies",
      doi: "10.30525/2256-0742/2019-5-3-213-217",
      abstract: "The purpose of the article is to justify the role of the fiscal strategy in ensuring macroeconomic stability and accelerating the pace of economic growth, disclose and substantiate its key objectives in the developed and transformational economies. The comparative and factor method allowed revealing the essence and role of the fiscal strategy as an instrument of economic growth, identifying peculiarities and substantiating approaches to the management of uncertainty of fiscal strategies, reveali",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "the-macroeconomics-of-de-cashing-2017",
      model: "fpp",
      topic: "methodology",
      title: "The Macroeconomics of De-Cashing",
      authors: "Alexei Kireyev, AKireyev@imf.org",
      year: 2017,
      venue: "IMF Working Paper",
      doi: "10.5089/9781475589252.001",
      abstract: "The paper presents a simple framework for the analysis of the macroeconomic implications of de-cashing. Defined as replacing paper currency with convertible deposits, de-cashing would affect all key macroeconomic sectors. The overall macreconomic impact of de-cashing would depend on the balance of growth-enhancing and growth-constraining factors. Starting from a traditional saving-investment balance, the paper develops a four-sector macroeconomic framework. It is purely illustrative and is desig",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "does-islamic-banking-really-strengthen-f-2017",
      model: "fpp",
      topic: "methodology",
      title: "Does Islamic banking really strengthen financial stability? Empirical evidence from Pakistan",
      authors: "Abdul Rashid, Saba Yousaf, Muhammad Khaleequzzaman",
      year: 2017,
      venue: "International Journal of Islamic and Middle Eastern Finance and Management",
      doi: "10.1108/imefm-11-2015-0137",
      abstract: "Purpose This paper aims to empirically assess the contribution of Islamic banks toward the financial stability of Pakistan. For this, the authors investigate the relative financial strength of Islamic banks and their contribution toward the financial stability. They also examine the relationship between the competitive conduct of banks and banking system stability. Design/methodology/approach The authors use quarterly data of ten conventional banks, four full-fledged Islamic banks and six standa",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
    {
      id: "the-international-monetary-fund-and-the-2014",
      model: "fpp",
      topic: "methodology",
      title: "The International Monetary Fund and the Ebola outbreak",
      authors: "Alexander Kentikelenis, Lawrence King, Martin McKee, David Stückler",
      year: 2014,
      venue: "The Lancet Global Health",
      doi: "10.1016/s2214-109x(14)70377-8",
      abstract: "In recent months, the International Monetary Fund (IMF) has announced US$430 million of funding to fight Ebola in Sierra Leone, Guinea, and Liberia.1Wintour P IMF to provide $300m in extra funding to help fight Ebola.The Guardian. Nov 15, 2014; (accessed Dec 15, 2014).http://www.theguardian.com/world/2014/nov/15/ebola-imf-set-to-unveil-debt-relief-at-g20-for-worst-affected-countriesGoogle Scholar By making these funds available, the IMF aims to become part of the solution to the crisis, even if ",
      relevance: {
        en: "",
        ru: "",
        uz: "",
      },
    },
  ],
};
