window.LITERATURE_DATA = {
  meta: {
    version: "0.2.0",
    lastUpdated: "2026-04-16",
  },
  modelLabels: {
    qpm: { en: "QPM", ru: "КПМ", uz: "CPM" },
    dfm: { en: "DFM", ru: "ДФМ", uz: "DFM" },
    cge: { en: "CGE", ru: "CGE", uz: "CGE" },
    io: { en: "Input-Output", ru: "Межотраслевой баланс", uz: "Tarmoqlararo balans" },
    pe: { en: "Partial Equilibrium", ru: "Частичное равновесие", uz: "Qisman muvozanat" },
    fpp: { en: "FPP", ru: "ФПП", uz: "MDS" },
  },
  papers: [
    /* ── QPM ── */
    {
      id: "berg-2006-qpm",
      model: "qpm",
      topic: "monetary",
      title: "Quarterly Projection Model for Small Open Economies",
      authors: "Berg, A., Karam, P., Laxton, D.",
      year: 2006,
      venue: "IMF Working Paper WP/06/185",
      doi: "10.5089/9781451863322.001",
      url: "https://www.imf.org/external/pubs/ft/wp/2006/wp06185.pdf",
      abstract: "Develops a tractable quarterly projection model for inflation-targeting central banks in small open economies, with IS curve, Phillips curve, Taylor rule, and UIP.",
      relevance: {
        en: "Foundational design template for the QPM — IS/Phillips/Taylor/UIP structure and calibration approach.",
        ru: "Базовый шаблон построения КПМ — структура IS/Филлипса/Тейлора/UIP и подход к калибровке.",
        uz: "CPM uchun asosiy dizayn andozasi — IS/Fillips/Teylor/UIP tuzilishi va kalibrlash yondashuvi.",
      },
    },
    {
      id: "laxton-2009-fpas",
      model: "qpm",
      topic: "monetary",
      title: "The Forecasting and Policy Analysis System at the Central Bank of Chile",
      authors: "Laxton, D., Rose, D., Scott, A.",
      year: 2009,
      venue: "IMF Working Paper WP/09/29",
      doi: "10.5089/9781451871654.001",
      url: "https://www.imf.org/external/pubs/ft/wp/2009/wp0929.pdf",
      abstract: "Operational architecture linking core QPM model to forecast rounds, fan charts, and policy communication at a central bank.",
      relevance: {
        en: "Useful for institutionalizing the forecast-policy workflow around the QPM at the CBU.",
        ru: "Полезно для институционализации цикла прогноз-политика вокруг КПМ в ЦБ.",
        uz: "MB da CPM atrofida prognoz-siyosat ish jarayonini tashkil etishda foydali.",
      },
    },
    {
      id: "imf-qpm-low-income-2017",
      model: "qpm",
      topic: "monetary",
      title: "Monetary Policy Transmission in Developing Countries: Evidence from India",
      authors: "Mishra, P., Montiel, P., Spilimbergo, A.",
      year: 2012,
      venue: "IMF Working Paper WP/12/143",
      doi: "10.5089/9781475504101.001",
      url: "https://www.imf.org/external/pubs/ft/wp/2012/wp12143.pdf",
      abstract: "Examines monetary policy transmission in developing countries with underdeveloped financial markets, relevant to QPM calibration for Uzbekistan.",
      relevance: {
        en: "Informs QPM calibration for economies with weak monetary transmission and shallow FX markets.",
        ru: "Информирует калибровку КПМ для экономик со слабой денежной трансмиссией.",
        uz: "Pul-kredit uzatmasi zaif iqtisodiyotlar uchun CPM kalibrlashni ma'lumot bilan ta'minlaydi.",
      },
    },

    /* ── DFM ── */
    {
      id: "banbura-2014-dfm",
      model: "dfm",
      topic: "nowcasting",
      title: "Maximum Likelihood Estimation of Factor Models on Datasets with Arbitrary Pattern of Missing Data",
      authors: "Banbura, M., Modugno, M.",
      year: 2014,
      venue: "Journal of Applied Econometrics, 29(1), 133-160",
      doi: "10.1002/jae.2306",
      url: "https://onlinelibrary.wiley.com/doi/10.1002/jae.2306",
      abstract: "ML estimation approach for large mixed-frequency datasets with ragged edges and arbitrary missing patterns.",
      relevance: {
        en: "Core methodology for handling missing data in the DFM Kalman filter nowcasting engine.",
        ru: "Основная методология обработки пропусков в системе nowcast DFM на основе фильтра Калмана.",
        uz: "DFM Kalman filtri nowcast tizimida yetishmayotgan ma'lumotlarni qayta ishlash metodologiyasi.",
      },
    },
    {
      id: "giannone-2008-nowcasting",
      model: "dfm",
      topic: "nowcasting",
      title: "Nowcasting: The Real-Time Informational Content of Macroeconomic Data",
      authors: "Giannone, D., Reichlin, L., Small, D.",
      year: 2008,
      venue: "Journal of Monetary Economics, 55(4), 665-676",
      doi: "10.1016/j.jmoneco.2008.05.010",
      url: "https://doi.org/10.1016/j.jmoneco.2008.05.010",
      abstract: "Classical nowcasting framework combining staggered data releases into current-quarter GDP estimates via dynamic factor models.",
      relevance: {
        en: "Canonical reference for release-calendar aware nowcasting and news decomposition.",
        ru: "Каноническая работа по nowcast с учетом календаря публикаций и разложению новостей.",
        uz: "Nashr taqvimi hisobga olingan nowcast va yangiliklar dekompozitsiyasi uchun klassik manba.",
      },
    },
    {
      id: "doz-2012-em-dfm",
      model: "dfm",
      topic: "nowcasting",
      title: "A Quasi-Maximum Likelihood Approach for Large, Approximate Dynamic Factor Models",
      authors: "Doz, C., Giannone, D., Reichlin, L.",
      year: 2012,
      venue: "Review of Economics and Statistics, 94(4), 1014-1024",
      doi: "10.1162/REST_a_00225",
      url: "https://doi.org/10.1162/REST_a_00225",
      abstract: "Two-step QML estimation combining principal components with Kalman smoothing for large panel datasets.",
      relevance: {
        en: "Alternative estimation approach relevant to scaling DFM with 34+ indicators.",
        ru: "Альтернативный подход к оценке для масштабирования DFM с 34+ индикаторами.",
        uz: "34+ ko'rsatkichlar bilan DFMni kengaytirish uchun muqobil baholash yondashuvi.",
      },
    },

    /* ── CGE ── */
    {
      id: "devarajan-1990-cge",
      model: "cge",
      topic: "trade",
      title: "Simple General Equilibrium Modeling",
      authors: "Devarajan, S., Lewis, J., Robinson, S.",
      year: 1990,
      venue: "World Development, 18(10), 1375-1398",
      doi: "10.1016/0305-750X(90)90006-2",
      url: "https://doi.org/10.1016/0305-750X(90)90006-2",
      abstract: "Compact CGE structure suitable for policy counterfactuals in developing economies with limited data.",
      relevance: {
        en: "Methodological backbone for the 1-2-3 style CGE module — CET/CES/closure approach.",
        ru: "Методологическая основа модуля CGE 1-2-3 — подход CET/CES/замыкание.",
        uz: "CGE 1-2-3 moduli uchun metodologik asos — CET/CES/yopilish yondashuvi.",
      },
    },
    {
      id: "devarajan-1997-123",
      model: "cge",
      topic: "trade",
      title: "The 1-2-3 DSGE Model: A Practical Guide for Analysis in Developing Countries",
      authors: "Devarajan, S., Go, D., Lewis, J., Robinson, S., Sinko, P.",
      year: 1997,
      venue: "World Bank Policy Research Working Paper No. 1893",
      doi: "10.1596/1813-9450-1893",
      url: "https://doi.org/10.1596/1813-9450-1893",
      abstract: "Practical closure rules, calibration guidance, and worked examples for trade and fiscal experiments in the 1-2-3 framework.",
      relevance: {
        en: "Provides the closure conventions and calibration protocols used in Uzbekistan CGE simulations.",
        ru: "Дает правила замыкания и протоколы калибровки для CGE-симуляций Узбекистана.",
        uz: "O'zbekiston CGE simulyatsiyalari uchun yopilish qoidalari va kalibrlash protokollarini beradi.",
      },
    },
    {
      id: "armington-1969",
      model: "cge",
      topic: "trade",
      title: "A Theory of Demand for Products Distinguished by Place of Production",
      authors: "Armington, P.S.",
      year: 1969,
      venue: "IMF Staff Papers, 16(1), 159-178",
      doi: "10.2307/3866403",
      url: "https://doi.org/10.2307/3866403",
      abstract: "Foundational import-demand assumption distinguishing goods by origin, used in virtually all applied CGE models.",
      relevance: {
        en: "Theoretical basis for the CES import-substitution block (σ_q = 0.70) in the CGE module.",
        ru: "Теоретическая основа блока импортозамещения CES (σ_q = 0.70) в модуле CGE.",
        uz: "CGE modulidagi CES import o'rnini bosish bloki (σ_q = 0.70) uchun nazariy asos.",
      },
    },
    {
      id: "lofgren-2002-standard-cge",
      model: "cge",
      topic: "trade",
      title: "A Standard Computable General Equilibrium Model in GAMS",
      authors: "Lofgren, H., Harris, R., Robinson, S.",
      year: 2002,
      venue: "IFPRI TMD Discussion Paper No. 75",
      doi: "",
      url: "https://www.ifpri.org/publication/standard-computable-general-equilibrium-cge-model-gams",
      abstract: "Standard CGE model documentation with SAM-based calibration, widely used as reference implementation.",
      relevance: {
        en: "Reference implementation for CGE calibration from SAM data — informs our 2021 base-year setup.",
        ru: "Эталонная реализация калибровки CGE из SAM — информирует нашу настройку базового 2021 года.",
        uz: "SAM ma'lumotlaridan CGE kalibrlashning etalon amalga oshirilishi — 2021 bazaviy yil sozlamalarini shakllantiradi.",
      },
    },

    /* ── IO ── */
    {
      id: "leontief-1986-io",
      model: "io",
      topic: "multipliers",
      title: "Input-Output Economics",
      authors: "Leontief, W.",
      year: 1986,
      venue: "Oxford University Press (2nd edition)",
      doi: "10.1093/0195035275.001.0001",
      url: "https://global.oup.com/academic/product/input-output-economics-9780195035278",
      abstract: "Foundational treatment of inter-industry linkage analysis, technical coefficients, and multiplier mechanics.",
      relevance: {
        en: "Primary conceptual source for output and value-added multiplier interpretation in the 136-sector model.",
        ru: "Базовый источник для интерпретации мультипликаторов выпуска и ДС в 136-секторной модели.",
        uz: "136-tarmoqli modelda ishlab chiqarish va QQ multiplikatorlarini talqin qilishning asosiy manbasi.",
      },
    },
    {
      id: "miller-blair-2009",
      model: "io",
      topic: "multipliers",
      title: "Input-Output Analysis: Foundations and Extensions",
      authors: "Miller, R.E., Blair, P.D.",
      year: 2009,
      venue: "Cambridge University Press (2nd edition)",
      doi: "10.1017/CBO9780511626982",
      url: "https://doi.org/10.1017/CBO9780511626982",
      abstract: "Comprehensive modern reference on I-O coefficients, Type I/II multipliers, structural decomposition, and regional extensions.",
      relevance: {
        en: "Supports multiplier diagnostics, Rasmussen classification, and sector linkage analysis.",
        ru: "Поддерживает диагностику мультипликаторов, классификацию Расмуссена и анализ отраслевых связей.",
        uz: "Multiplikator diagnostikasi, Rasmussen klassifikatsiyasi va tarmoq aloqalari tahlilini qo'llab-quvvatlaydi.",
      },
    },
    {
      id: "temursho-2017-io",
      model: "io",
      topic: "multipliers",
      title: "Analytical and Empirical Comparisons of Input-Output Multipliers",
      authors: "Temursho, U.",
      year: 2017,
      venue: "Journal of Economic Surveys, 31(3), 921-940",
      doi: "10.1111/joes.12167",
      url: "https://doi.org/10.1111/joes.12167",
      abstract: "Systematic comparison of Type I, II, and SAM-based multipliers with empirical evidence on bias and policy relevance.",
      relevance: {
        en: "Informs choice between Type I (current) and Type II multipliers for future IO model upgrades.",
        ru: "Информирует выбор между мультипликаторами Типа I (текущий) и Типа II для будущих обновлений МОБ.",
        uz: "Kelajakdagi MOB yangilanishlari uchun I Tip (joriy) va II Tip multiplikatorlari o'rtasida tanlashga yordam beradi.",
      },
    },

    /* ── PE ── */
    {
      id: "wits-smart-guide",
      model: "pe",
      topic: "trade",
      title: "WITS-SMART Simulation Tool: User Guide and Methodology",
      authors: "World Bank WITS Team",
      year: 2020,
      venue: "World Bank Technical Manual",
      doi: "",
      url: "https://wits.worldbank.org/wits/wits/witshelp/Content/SMART/SMART.htm",
      abstract: "Documentation of SMART partial equilibrium formulas for trade creation, trade diversion, consumer surplus, and tariff revenue calculations.",
      relevance: {
        en: "Direct specification source for PE trade creation/diversion formulas (TC, TD, welfare).",
        ru: "Прямой источник спецификации формул создания/отклонения торговли в модели ЧР.",
        uz: "QM savdo yaratish/chetga surilish formulalari uchun bevosita spetsifikatsiya manbasi.",
      },
    },
    {
      id: "laird-yeats-1990",
      model: "pe",
      topic: "trade",
      title: "Quantitative Methods for Trade Barrier Analysis",
      authors: "Laird, S., Yeats, A.",
      year: 1990,
      venue: "London: Macmillan",
      doi: "10.1007/978-1-349-20685-3",
      url: "https://doi.org/10.1007/978-1-349-20685-3",
      abstract: "Classical partial-equilibrium methods for tariff incidence, effective protection, and welfare analysis of trade liberalization.",
      relevance: {
        en: "Provides assumptions and interpretation standards for PE welfare metrics used in WTO scenarios.",
        ru: "Задает предпосылки и стандарты интерпретации показателей благосостояния для сценариев ВТО.",
        uz: "VTS stsenariylari uchun farovonlik ko'rsatkichlarini talqin qilish standartlarini beradi.",
      },
    },
    {
      id: "brenton-2001-wto",
      model: "pe",
      topic: "trade",
      title: "Trade Policy Reform and the WTO Accession of Transition Economies",
      authors: "Brenton, P., Manchin, M.",
      year: 2003,
      venue: "World Bank Policy Research Working Paper No. 3012",
      doi: "10.1596/1813-9450-3012",
      url: "https://doi.org/10.1596/1813-9450-3012",
      abstract: "Analysis of WTO accession trade impacts for transition economies using partial equilibrium methods.",
      relevance: {
        en: "Directly relevant to Uzbekistan's WTO accession trade impact analysis using PE methods.",
        ru: "Непосредственно относится к анализу торговых последствий вступления Узбекистана в ВТО.",
        uz: "O'zbekistonning VSTga qo'shilishining savdoga ta'sirini QM usullari bilan tahlil qilishga bevosita aloqador.",
      },
    },

    /* ── FPP ── */
    {
      id: "imf-fp-manual-2013",
      model: "fpp",
      topic: "fiscal",
      title: "Financial Programming and Policies",
      authors: "IMF Institute for Capacity Development",
      year: 2013,
      venue: "IMF Training Manual (2 volumes)",
      doi: "",
      url: "https://www.imf.org/en/Capacity-Development/Training/ICDTC/Courses/FPP",
      abstract: "Integrated macro-consistency framework linking real, fiscal, external, and monetary sectors through accounting identities and behavioral equations.",
      relevance: {
        en: "Core reference for the 4-sector consistency checks and accounting identities in the FPP module.",
        ru: "Ключевой источник по 4-секторным проверкам согласованности и тождествам в модуле ФПП.",
        uz: "MDS modulidagi 4-sektorli moslik tekshiruvlari va hisob identifikatsiyalari uchun asosiy manba.",
      },
    },
    {
      id: "mussa-savastano-1999",
      model: "fpp",
      topic: "fiscal",
      title: "The IMF Approach to Economic Stabilization",
      authors: "Mussa, M., Savastano, M.",
      year: 1999,
      venue: "NBER Macroeconomics Annual 1999, Vol. 14, 79-122",
      doi: "10.1086/654424",
      url: "https://doi.org/10.1086/654424",
      abstract: "Discussion of IMF stabilization program design, policy consistency checks, and conditionality trade-offs.",
      relevance: {
        en: "Useful framing for translating FPP simulation outputs into stabilization policy narratives.",
        ru: "Полезная рамка для перевода результатов ФПП в рекомендации по стабилизационной политике.",
        uz: "MDS simulyatsiya natijalarini barqarorlashtirish siyosati tavsiyalariga aylantirish uchun foydali yondashuv.",
      },
    },
    {
      id: "polak-1957-monetary",
      model: "fpp",
      topic: "monetary",
      title: "Monetary Analysis of Income Formation and Payments Problems",
      authors: "Polak, J.J.",
      year: 1957,
      venue: "IMF Staff Papers, 6(1), 1-50",
      doi: "10.2307/3866128",
      url: "https://doi.org/10.2307/3866128",
      abstract: "The foundational monetary approach to the balance of payments — origin of the IMF Financial Programming framework.",
      relevance: {
        en: "Historical foundation of the monetary-BOP link in financial programming (NFA + NDA = M2).",
        ru: "Историческая основа связи монетарный сектор — платежный баланс в ФП (ЧИА + ЧВА = M2).",
        uz: "Moliyaviy dasturlashdagi pul-to'lov balansi aloqasining tarixiy asosi (STF + IKA = M2).",
      },
    },
  ],
};
