window.RESEARCH_DATA = {
  meta: {
    version: "0.1.0",
    lastUpdated: "2026-04-16",
  },
  topics: {
    trade: { label: { en: "Trade", ru: "Торговля", uz: "Savdo" }, color: "#14b8a6" },
    monetary: { label: { en: "Monetary", ru: "Монетарная", uz: "Monetar" }, color: "#8b5cf6" },
    fiscal: { label: { en: "Fiscal", ru: "Фискальная", uz: "Fiskal" }, color: "#f59e0b" },
    growth: { label: { en: "Growth", ru: "Рост", uz: "O'sish" }, color: "#2563eb" },
    inflation: { label: { en: "Inflation", ru: "Инфляция", uz: "Inflyatsiya" }, color: "#ef4444" },
    structural: { label: { en: "Structural", ru: "Структурная", uz: "Tarkibiy" }, color: "#10b981" },
  },
  entries: [
    {
      id: "brief-wto-readiness-2026",
      title: { en: "WTO Readiness: Tariff Pathways and Transition Costs", ru: "Готовность к ВТО: тарифные траектории и издержки перехода", uz: "JTOga tayyorgarlik: tarif yo'nalishlari va o'tish xarajatlari" },
      author: "CERR Trade Team",
      date: "2026-03-22",
      model: "pe",
      topics: ["trade", "growth"],
      abstract: {
        en: "Simulation evidence on phased MFN tariff cuts and sector-level adjustment pressure.",
        ru: "Сценарный анализ поэтапного снижения НБН тарифов и секторального давления адаптации.",
        uz: "Bosqichma-bosqich MFN tariflarini kamaytirish va tarmoqlar moslashuv bosimi bo'yicha ssenariy tahlili.",
      },
      body: {
        en: "A calibrated PE simulation shows welfare gains concentrated in machinery and intermediate goods while fiscal losses are front-loaded. Transitional support is recommended for affected customs-intensive sectors.",
        ru: "Калиброванная модель ЧР показывает, что выигрыш благосостояния сосредоточен в машиностроении и промежуточных товарах, тогда как фискальные потери проявляются в начале периода. Для уязвимых отраслей рекомендована переходная поддержка.",
        uz: "Kalibrlangan QM natijalari farovonlik yutuqlari asosan mashinasozlik va oraliq tovarlarda to'planishini, fiskal yo'qotishlar esa dastlabki bosqichda yuqori bo'lishini ko'rsatadi. Ta'sirchan tarmoqlar uchun o'tish davri qo'llovi tavsiya etiladi.",
      },
    },
    {
      id: "policy-rate-transmission-qpm-2026",
      title: { en: "Policy Rate Transmission Under Current Inflation Dynamics", ru: "Передача ключевой ставки в текущей инфляционной динамике", uz: "Joriy inflyatsion sharoitda asosiy stavka uzatmasi" },
      author: "Monetary Policy Unit",
      date: "2026-02-28",
      model: "qpm",
      topics: ["monetary", "inflation"],
      abstract: {
        en: "QPM-based stress test of rate hikes under alternative exchange-rate pass-through assumptions.",
        ru: "Стресс-тест КПМ для повышения ставки при разных допущениях по курсовому переносу.",
        uz: "Valyuta kursi o'tkazuvchanligi turli taxminlari ostida stavka oshirish bo'yicha CPM stress-testi.",
      },
      body: {
        en: "Higher imported inflation sensitivity increases the policy rate required to return inflation to target. Communication and expectation anchoring reduce output-gap volatility in all tested paths.",
        ru: "Более высокая чувствительность к импортируемой инфляции повышает требуемую ключевую ставку для возврата инфляции к цели. Коммуникация и якорение ожиданий снижают волатильность разрыва выпуска во всех сценариях.",
        uz: "Import inflyatsiyasiga sezgirlik yuqori bo'lganda maqsadga qaytish uchun zarur stavka darajasi oshadi. Kommunikatsiya va kutilmalarni mustahkamlash barcha ssenariylarda ishlab chiqarish tafovuti o'zgaruvchanligini kamaytiradi.",
      },
    },
    {
      id: "energy-pricing-fiscal-space-2026",
      title: { en: "Energy Pricing Reform and Fiscal Space", ru: "Реформа тарифов на энергию и фискальное пространство", uz: "Energiya tariflari islohoti va fiskal makon" },
      author: "Fiscal Sustainability Group",
      date: "2026-03-08",
      model: "fpp",
      topics: ["fiscal", "inflation"],
      abstract: {
        en: "Assessment of subsidy rationalization under inflation and social-protection constraints.",
        ru: "Оценка оптимизации субсидий при ограничениях по инфляции и соцзащите.",
        uz: "Inflyatsiya va ijtimoiy himoya cheklovlari ostida subsidiyalarni optimallashtirish bahosi.",
      },
      body: {
        en: "Phased tariff normalization improves budget balance and reserve adequacy indicators, but requires a targeted compensation envelope to preserve real incomes for vulnerable households.",
        ru: "Поэтапная нормализация тарифов улучшает бюджетный баланс и показатели резервной устойчивости, но требует адресной компенсации для сохранения реальных доходов уязвимых домохозяйств.",
        uz: "Tariflarni bosqichma-bosqich normallashtirish byudjet balansi va rezerv barqarorligini yaxshilaydi, biroq zaif uy xo'jaliklari real daromadini saqlash uchun manzilli kompensatsiya paketini talab qiladi.",
      },
    },
    {
      id: "nowcast-volatility-monitor-2026",
      title: { en: "Nowcast Volatility Monitor: Q1 Signal Decomposition", ru: "Монитор волатильности прогнозов: декомпозиция сигналов Q1", uz: "Nowcast o'zgaruvchanlik monitoringi: Q1 signal dekompozitsiyasi" },
      author: "Nowcasting Lab",
      date: "2026-04-01",
      model: "dfm",
      topics: ["growth", "inflation"],
      abstract: {
        en: "Indicator-level contribution analysis behind monthly revisions in GDP nowcasts.",
        ru: "Анализ вклада индикаторов в ежемесячные пересмотры прогноза ВВП.",
        uz: "YaIM nowcast oylik qayta ko'rib chiqilishida indikatorlar hissasi tahlili.",
      },
      body: {
        en: "Industrial output and electricity use drove positive revisions, while softer retail turnover partially offset gains. The mixed-frequency filter remains stable under data-release lags.",
        ru: "Положительные пересмотры обеспечили промышленный выпуск и потребление электроэнергии, тогда как ослабление розничного оборота частично ограничило рост. Фильтр смешанной частоты остается устойчивым при лагах публикации данных.",
        uz: "Ijobiy qayta baholashga sanoat ishlab chiqarishi va elektr iste'moli hissa qo'shdi, chakana savdo pasayishi esa qisman kompensatsiya qildi. Aralash chastotali filtr ma'lumotlar kechikishida ham barqaror ishladi.",
      },
    },
    {
      id: "regional-clusters-io-2025",
      title: { en: "Regional Cluster Spillovers in the 2022 I-O Table", ru: "Эффекты региональных кластеров в таблице МОБ 2022", uz: "2022-yil TMB jadvalida hududiy klaster spilloverlari" },
      author: "Industrial Policy Team",
      date: "2025-12-15",
      model: "io",
      topics: ["growth", "structural"],
      abstract: {
        en: "Multiplier ranking for manufacturing clusters and logistics corridors.",
        ru: "Рейтинг мультипликаторов для промышленных кластеров и логистических коридоров.",
        uz: "Sanoat klasterlari va logistika koridorlari uchun multiplikator reytingi.",
      },
      body: {
        en: "Backward linkages are strongest in chemicals, machinery, and construction materials. Regional targeting can raise value-added intensity with moderate import leakage.",
        ru: "Наиболее сильные обратные связи наблюдаются в химии, машиностроении и стройматериалах. Региональное таргетирование может повысить интенсивность добавленной стоимости при умеренной импортной утечке.",
        uz: "Orqaga bog'liqliklar kimyo, mashinasozlik va qurilish materiallarida kuchli. Hududiy nishonlash import sizib chiqishi mo''tadil bo'lgan holda qo'shilgan qiymat intensivligini oshiradi.",
      },
    },
    {
      id: "cge-fdi-absorption-2026",
      title: { en: "FDI Absorption Capacity Under Alternative Trade Closures", ru: "Поглощение ПИИ при альтернативных торговых замыканиях", uz: "Savdo yopilishlari bo'yicha TOI yutilish salohiyati" },
      author: "CGE Group",
      date: "2026-01-18",
      model: "cge",
      topics: ["trade", "structural", "growth"],
      abstract: {
        en: "CGE scenarios on productivity, import intensity, and real exchange-rate adjustment.",
        ru: "Сценарии CGE по производительности, импортной интенсивности и корректировке реального курса.",
        uz: "Unumdorlik, import intensivligi va real kurs moslashuvi bo'yicha CGE ssenariylari.",
      },
      body: {
        en: "FDI-led expansion yields stronger growth when domestic supplier depth improves. Exchange-rate flexibility reduces adjustment costs in tradable sectors.",
        ru: "Рост, основанный на ПИИ, сильнее при углублении сети внутренних поставщиков. Гибкий обменный курс снижает издержки адаптации в торгуемых секторах.",
        uz: "TOI asosidagi kengayish ichki ta'minot zanjiri chuqurlashganda kuchliroq o'sishni beradi. Moslashuvchan kurs savdo qilinadigan tarmoqlarda moslashuv xarajatlarini kamaytiradi.",
      },
    },
    {
      id: "agri-water-productivity-2026",
      title: { en: "Agricultural Water Productivity and Export Competitiveness", ru: "Водная продуктивность в сельском хозяйстве и экспортная конкурентоспособность", uz: "Qishloq xo'jaligida suv unumdorligi va eksport raqobatbardoshligi" },
      author: "Agriculture Desk",
      date: "2026-03-03",
      model: "cge",
      topics: ["structural", "trade"],
      abstract: {
        en: "Sector simulations linking irrigation efficiency gains with export response.",
        ru: "Секторальные симуляции связи роста эффективности орошения и экспортной динамики.",
        uz: "Sug'orish samaradorligi o'sishi va eksport javobi o'rtasidagi bog'liqlik bo'yicha sektor simulyatsiyalari.",
      },
      body: {
        en: "Water-efficiency gains improve agricultural cost structure and export margins, with strongest effects in horticulture chains.",
        ru: "Рост водоэффективности улучшает издержки сельского хозяйства и экспортную маржу, особенно в цепочках плодоовощной продукции.",
        uz: "Suv samaradorligi oshishi qishloq xo'jaligi xarajat tuzilmasi va eksport marjasini yaxshilaydi, eng katta ta'sir meva-sabzavot zanjirlarida kuzatiladi.",
      },
    },
    {
      id: "banking-credit-allocation-2026",
      title: { en: "Credit Allocation After Banking Liberalization", ru: "Распределение кредита после либерализации банковского сектора", uz: "Bank liberallashuvidan keyin kredit taqsimoti" },
      author: "Financial Markets Team",
      date: "2026-02-11",
      model: "fpp",
      topics: ["monetary", "growth"],
      abstract: {
        en: "Early evidence on credit rebalancing toward private firms.",
        ru: "Первые результаты перераспределения кредита в пользу частного сектора.",
        uz: "Kreditning xususiy sektorga qayta taqsimlanishi bo'yicha dastlabki natijalar.",
      },
      body: {
        en: "Credit composition is gradually shifting from directed programs toward market-based lending. SME access improves where collateral registries are digitized.",
        ru: "Структура кредита постепенно смещается от директивных программ к рыночному кредитованию. Доступ МСП улучшается в регионах с цифровыми реестрами залога.",
        uz: "Kredit tarkibi direktiv dasturlardan bozor kreditlashiga bosqichma-bosqich o'tmoqda. Garov reyestrlari raqamlashtirilgan hududlarda KOBlar kirishi yaxshilanmoqda.",
      },
    },
    {
      id: "customs-single-window-impact-2026",
      title: { en: "Customs Single Window: Border Time and Compliance Effects", ru: "Единое окно на таможне: эффекты на время и соблюдение требований", uz: "Bojxonadagi yagona darcha: vaqt va moslikka ta'siri" },
      author: "Trade Facilitation Unit",
      date: "2026-01-30",
      model: "pe",
      topics: ["trade", "structural"],
      abstract: {
        en: "Assessment of processing-time reductions and importer response.",
        ru: "Оценка сокращения времени обработки и реакции импортеров.",
        uz: "Qayta ishlash vaqti qisqarishi va importerlar javobini baholash.",
      },
      body: {
        en: "Clearance-time reductions correlate with larger formal import flows and lower variance in customs-value declarations.",
        ru: "Сокращение времени оформления связано с ростом формального импорта и меньшей вариативностью таможенной стоимости.",
        uz: "Rasmiylashtirish vaqtining qisqarishi rasmiy import oqimlarining o'sishi va bojxona qiymati deklaratsiyasidagi o'zgaruvchanlik pasayishi bilan bog'liq.",
      },
    },
    {
      id: "inflation-expectations-brief-2026",
      title: { en: "Inflation Expectations Monitor: Household and Firm Signals", ru: "Монитор инфляционных ожиданий: сигналы домохозяйств и фирм", uz: "Inflyatsion kutilmalar monitori: uy xo'jaliklari va firmalar signallari" },
      author: "Macroeconomic Analysis Division",
      date: "2026-04-10",
      model: "qpm",
      topics: ["inflation", "monetary"],
      abstract: {
        en: "Expectation dispersion and policy communication implications.",
        ru: "Дисперсия ожиданий и выводы для коммуникации политики.",
        uz: "Kutilmalar dispersiyasi va siyosat kommunikatsiyasi uchun xulosalar.",
      },
      body: {
        en: "Firm expectations re-anchor faster than households after rate guidance updates. Communication frequency materially affects short-horizon inflation beliefs.",
        ru: "Ожидания фирм возвращаются к якорю быстрее, чем ожидания домохозяйств, после обновления guidance по ставке. Частота коммуникации заметно влияет на краткосрочные инфляционные ожидания.",
        uz: "Stavka bo'yicha yo'riqnoma yangilangach, firmalar kutilmalari uy xo'jaliklariga qaraganda tezroq barqarorlashadi. Kommunikatsiya chastotasi qisqa muddatli inflyatsion kutilmalarga sezilarli ta'sir qiladi.",
      },
    },
  ],
};
