import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import i18next from 'i18next'
import { initReactI18next, I18nextProvider } from 'react-i18next'
import { renderToStaticMarkup } from 'react-dom/server'
import { InterpretationPanel } from '../../../src/components/scenario-lab/InterpretationPanel.js'
import type { ScenarioLabInterpretation } from '../../../src/contracts/data-contract.js'

type InterpretationWithMetadata = ScenarioLabInterpretation & {
  generation_mode?: 'template' | 'assisted' | 'reviewed'
  reviewer_name?: string
  reviewed_at?: string
}

async function createTestI18n() {
  const instance = i18next.createInstance()
  await instance.use(initReactI18next).init({
    lng: 'en',
    fallbackLng: 'en',
    defaultNS: 'common',
    ns: ['common'],
    interpolation: { escapeValue: false },
    resources: {
      en: {
        common: {
          scenarioLab: {
            interpretation: {
              title: 'Interpretation',
              description: 'Translate model outputs into decision language.',
              sections: {
                whatChanged: 'What changed',
                whyItChanged: 'Why it changed',
                keyRisks: 'Key risks',
                policyImplications: 'Policy implications',
                suggestedNextScenarios: 'Suggested next scenarios',
              },
              aiAttribution: {
                assisted: {
                  title: 'AI-assisted · Unreviewed draft',
                  body:
                    'AI-assisted draft. Generated by model output, not yet reviewed by CERR analytical staff. Do not cite, export, or share externally.',
                },
                reviewed: {
                  title: 'AI-assisted · Reviewed {{reviewed_at}}',
                  body:
                    'AI-assisted narrative, reviewed by {{reviewer_name}} on {{review_date}}. Cleared for internal use and citation.',
                },
              },
            },
          },
        },
      },
    },
  })
  return instance
}

function buildInterpretation(overrides: Partial<InterpretationWithMetadata> = {}): InterpretationWithMetadata {
  return {
    what_changed: ['GDP growth softened.'],
    why_it_changed: ['External demand weakened.'],
    key_risks: ['Persistent imported inflation.'],
    policy_implications: ['Tighten policy sequencing.'],
    suggested_next_scenarios: ['External slowdown with fiscal consolidation.'],
    generation_mode: 'template',
    ...overrides,
  }
}

describe('InterpretationPanel', () => {
  it('renders template mode without ai attribution', async () => {
    const i18n = await createTestI18n()
    const markup = renderToStaticMarkup(
      <I18nextProvider i18n={i18n}>
        <InterpretationPanel interpretation={buildInterpretation({ generation_mode: 'template' })} />
      </I18nextProvider>,
    )

    assert.equal(markup.includes('ai-attribution'), false)
  })

  it('renders assisted mode with unreviewed disclaimer copy', async () => {
    const i18n = await createTestI18n()
    const markup = renderToStaticMarkup(
      <I18nextProvider i18n={i18n}>
        <InterpretationPanel interpretation={buildInterpretation({ generation_mode: 'assisted' })} />
      </I18nextProvider>,
    )

    assert.match(markup, /class="ai-attribution"/)
    assert.match(markup, /AI-assisted · Unreviewed draft/)
    assert.match(
      markup,
      /AI-assisted draft\. Generated by model output, not yet reviewed by CERR analytical staff\. Do not cite, export, or share externally\./,
    )
    assert.equal(markup.includes('ai-attribution--reviewed'), false)
  })

  it('renders reviewed mode with reviewed class and reviewer/date interpolation', async () => {
    const i18n = await createTestI18n()
    const markup = renderToStaticMarkup(
      <I18nextProvider i18n={i18n}>
        <InterpretationPanel
          interpretation={buildInterpretation({
            generation_mode: 'reviewed',
            reviewer_name: 'M. Usmanov',
            reviewed_at: '2026-04-20T09:15:00+05:00',
          })}
        />
      </I18nextProvider>,
    )

    assert.match(markup, /class="ai-attribution ai-attribution--reviewed"/)
    assert.match(markup, /AI-assisted · Reviewed/)
    assert.match(markup, /reviewed by M\. Usmanov/)
    assert.match(markup, /Cleared for internal use and citation\./)
  })
})
