import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import i18next from 'i18next'
import { initReactI18next, I18nextProvider } from 'react-i18next'
import { MemoryRouter } from 'react-router-dom'
import { renderToStaticMarkup } from 'react-dom/server'
import { InterpretationPanel } from '../../../src/components/scenario-lab/InterpretationPanel.js'
import type { ScenarioLabInterpretation } from '../../../src/contracts/data-contract.js'

async function createTestI18n() {
  const instance = i18next.createInstance()
  await instance.use(initReactI18next).init({
    lng: 'en',
    fallbackLng: 'en',
    defaultNS: 'common',
    ns: ['common'],
    interpolation: { escapeValue: false },
    resources: {
      en: {
        common: {
          scenarioLab: {
            interpretation: {
              title: 'Interpretation',
              description: 'Translate model outputs into decision language.',
              sections: {
                whatChanged: 'What changed',
                whyItChanged: 'Why it changed',
                keyRisks: 'Key risks',
                policyImplications: 'Policy implications',
                suggestedNextScenarios: 'Suggested next scenarios',
              },
              aiAttribution: {
                assisted: {
                  title: 'AI-assisted · Unreviewed draft',
                  body:
                    'AI-assisted draft. Generated by model output, not yet reviewed by CERR analytical staff. Do not cite, export, or share externally.',
                },
                reviewed: {
                  title: 'AI-assisted · Reviewed {{reviewed_at}}',
                  body:
                    'AI-assisted narrative, reviewed by {{reviewer_name}} on {{review_date}}. Cleared for internal use and citation.',
                },
              },
            },
          },
        },
      },
    },
  })
  return instance
}

function buildInterpretation(
  overrides: Partial<ScenarioLabInterpretation> = {},
): ScenarioLabInterpretation {
  return {
    what_changed: ['GDP growth softened.'],
    why_it_changed: ['External demand weakened.'],
    key_risks: ['Persistent imported inflation.'],
    policy_implications: ['Tighten policy sequencing.'],
    suggested_next_scenarios: ['External slowdown with fiscal consolidation.'],
    metadata: { generation_mode: 'template' },
    ...overrides,
  }
}

describe('InterpretationPanel', () => {
  it('does not render AI attribution treatment in template mode', async () => {
    const i18n = await createTestI18n()
    const markup = renderToStaticMarkup(
      <MemoryRouter>
        <I18nextProvider i18n={i18n}>
          <InterpretationPanel
            interpretation={buildInterpretation({ metadata: { generation_mode: 'template' } })}
          />
        </I18nextProvider>
      </MemoryRouter>,
    )

    assert.doesNotMatch(markup, /class="ai-attribution/)
    assert.doesNotMatch(markup, /AI-assisted/)
  })

  it('ignores legacy top-level governance fields without typed metadata', async () => {
    const i18n = await createTestI18n()
    const legacyInterpretation = {
      ...buildInterpretation({ metadata: undefined }),
      generation_mode: 'reviewed',
      reviewer_name: 'Legacy Reviewer',
      reviewed_at: '2026-04-20T09:15:00+05:00',
    } as ScenarioLabInterpretation
    const markup = renderToStaticMarkup(
      <MemoryRouter>
        <I18nextProvider i18n={i18n}>
          <InterpretationPanel interpretation={legacyInterpretation} />
        </I18nextProvider>
      </MemoryRouter>,
    )

    assert.doesNotMatch(markup, /class="ai-attribution/)
    assert.doesNotMatch(markup, /Legacy Reviewer/)
  })

  it('renders the adopted unreviewed warning in assisted mode', async () => {
    const i18n = await createTestI18n()
    const markup = renderToStaticMarkup(
      <MemoryRouter>
        <I18nextProvider i18n={i18n}>
          <InterpretationPanel
            interpretation={buildInterpretation({ metadata: { generation_mode: 'assisted' } })}
          />
        </I18nextProvider>
      </MemoryRouter>,
    )

    assert.match(markup, /class="ai-attribution ai-attribution--assisted"/)
    assert.match(markup, /AI-assisted · Unreviewed draft/)
    assert.match(markup, /Do not cite, export, or share externally/)
  })

  it('renders reviewer meta line when reviewed mode carries a reviewer name', async () => {
    const i18n = await createTestI18n()
    const markup = renderToStaticMarkup(
      <MemoryRouter>
        <I18nextProvider i18n={i18n}>
          <InterpretationPanel
            interpretation={buildInterpretation({
              metadata: {
                generation_mode: 'reviewed',
                reviewer_name: 'M. Usmanov',
                reviewed_at: '2026-04-20T09:15:00+05:00',
              },
            })}
          />
        </I18nextProvider>
      </MemoryRouter>,
    )

    assert.match(markup, /class="ai-attribution ai-attribution--reviewed"/)
    assert.match(markup, /AI-assisted · Reviewed/)
    assert.match(markup, /reviewed by M\. Usmanov/)
    assert.match(markup, /Cleared for internal use and citation/)
  })

  it('falls back to assisted treatment when reviewed metadata is incomplete', async () => {
    const i18n = await createTestI18n()
    const markup = renderToStaticMarkup(
      <MemoryRouter>
        <I18nextProvider i18n={i18n}>
          <InterpretationPanel
            interpretation={buildInterpretation({
              metadata: {
                generation_mode: 'reviewed',
                reviewer_name: 'M. Usmanov',
              },
            })}
          />
        </I18nextProvider>
      </MemoryRouter>,
    )

    assert.match(markup, /AI-assisted · Unreviewed draft/)
    assert.match(markup, /Do not cite, export, or share externally/)
    assert.doesNotMatch(markup, /Cleared for internal use and citation/)
  })

  it('renders clickable Link anchors for suggested_next entries', async () => {
    const i18n = await createTestI18n()
    const markup = renderToStaticMarkup(
      <MemoryRouter>
        <I18nextProvider i18n={i18n}>
          <InterpretationPanel
            interpretation={buildInterpretation({
              suggested_next: [
                {
                  label: 'Pair with a remittance shock',
                  target_route: '/scenario-lab',
                  target_preset: 'russia_slowdown',
                },
                {
                  label: 'Compare with baseline and tight-money',
                  target_route: '/comparison',
                },
              ],
            })}
          />
        </I18nextProvider>
      </MemoryRouter>,
    )

    assert.match(markup, /href="\/scenario-lab\?preset=russia_slowdown"/)
    assert.match(markup, /href="\/comparison"/)
  })
})
